name: Deploy preview

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # This is required for resolving the latest release tag

      - uses: actions/setup-node@v6
        with:
          node-version: 23

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v5
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Prepare preview
        # The preview widget is deployed on release only, so the constants point
        # to the latest released one.
        run: node prepare-release.mjs "$(git describe --tags --abbrev=0 2>/dev/null || echo 0.0.0-dev)"

      - name: Publish preview
        run: |-
          npx pkg-pr-new publish \
            --compact --comment=update \
            ./build
