name: Library validations

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - master
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  validations:
    uses: croct-tech/github-workflows/.github/workflows/javascript-validation.yml@unify-workflows
    with:
      node-version: '23'
      run-security: true
      use-private-registry: false
