name: Library validations

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - master
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  validations:
    uses: croct-tech/shared-public-configs/.github/workflows/javascript-validations.yml@master
    with:
      run-security: true
      use-private-registry: false
